plugin-enabled: true # Enables or disables the entire plugin

auto-save-enabled: true # automatically save data every so often to protect from crashes?
auto-save-timer: 300 # in seconds

blacklist-enabled: true
blacklist-is-whitelist: false # Toggle whether the item blacklist is actually an item whitelist
vault-item-blacklist: # Which items are people not allowed to put in their vaults?
  - BEDROCK
  - END_PORTAL_FRAME

config-version: 1.0